<a href="https://colab.research.google.com/github/Saksham-tyagi1/PyTorch-Basics/blob/main/PytorchBasicLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]],dtype='float32')
target = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]],dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(target)
print(inputs)
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [4]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.7533, -0.1400, -0.5563],
        [ 1.0021,  0.0817, -0.0456]], requires_grad=True)
tensor([-1.7704, -0.5604], requires_grad=True)


In [5]:
def model(x):
  return x @ w.t()+b

In [6]:
pred = model(inputs)
print(pred)

tensor([[ -90.0644,   76.1031],
        [-118.2468,   94.8979],
        [-118.3382,   94.9221],
        [-105.2106,  103.4759],
        [-106.1328,   73.2322]], grad_fn=<AddBackward0>)


In [7]:
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [8]:
loss = mse(pred,targets)
print(loss)

tensor(18532.0723, grad_fn=<DivBackward0>)


In [10]:
loss.backward()

In [11]:
print(w)
print(w.grad)

tensor([[-0.7533, -0.1400, -0.5563],
        [ 1.0021,  0.0817, -0.0456]], requires_grad=True)
tensor([[-15369.6445, -16934.0293, -10428.8535],
        [    40.0060,  -1353.1500,   -616.1502]])


In [12]:
w
w.grad

tensor([[-15369.6445, -16934.0293, -10428.8535],
        [    40.0060,  -1353.1500,   -616.1502]])

In [15]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [17]:
w.grad.zero_()
b.grad.zero_()


tensor([0., 0.])

In [18]:
pred = model(inputs)
print(pred)

tensor([[-63.0125,  77.2454],
        [-82.6822,  96.4467],
        [-76.2244,  97.0580],
        [-78.3914, 104.2450],
        [-71.9691,  74.9350]], grad_fn=<AddBackward0>)


In [19]:
loss = mse(pred,targets)

In [21]:
loss.backward()

In [22]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [23]:
pred = model(inputs)
loss = mse(pred,targets)
print(loss)

tensor(8865.3555, grad_fn=<DivBackward0>)


# Epoch

In [24]:
for i in range(100):
  pred = model(inputs)
  loss = mse(pred,targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [25]:
loss = mse(pred,targets)
print(loss)

tensor(272.4629, grad_fn=<DivBackward0>)
